services:
  game:
    build:
      context: .
      dockerfile: bench.dockerfile
    hostname: game
    networks:
      - backend
    environment:
      - LISTEN_ADDR=0.0.0.0:5000
    ports:
      - "5000:5000"
    command: ["/game"]
    deploy:
      resources:
          limits:
            cpus: "1.0"
    volumes:
      - db-data:/data
  
  bot_client:
    build:
      context: .
      dockerfile: bench.dockerfile
    hostname: bot_client
    depends_on:
      - game
    networks:
      - backend
    environment:
      - SERVER_ADDR=game:5000
    command: ["/bot_client"]
    volumes:
      - db-data:/data

networks:
  backend:
    driver: bridge

volumes:
  db-data: