services:
  game:
    build:
      context: .
      dockerfile: bench.dockerfile
    hostname: game
    networks:
      - backend
    environment:
      - LISTEN_ADDR=0.0.0.0:5000
      - BOT_COUNT=${BOT_COUNT}
      - INITIAL_SERVER_COUNT=${INITIAL_SERVER_COUNT}
      - EXPERIMENT_ID=${EXPERIMENT_ID}
      - MAX_TICKS=10000
    ports:
      - "5000:5000"
    command: ["/game"]
    restart: no
    deploy:
      resources:
          limits:
            cpus: "2.0"
    volumes:
      - db-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 2s
      timeout: 2s
      retries: 3
  
  bot_client:
    build:
      context: .
      dockerfile: bench.dockerfile
    hostname: bot_client
    restart: no
    depends_on:
      game:
        condition: service_healthy
    networks:
      - backend
    environment:
      - SERVER_ADDR=game:5000
      - BOT_COUNT=${BOT_COUNT}
      - INITIAL_SERVER_COUNT=${INITIAL_SERVER_COUNT}
      - EXPERIMENT_ID=${EXPERIMENT_ID}
    command: ["/bot_client"]
    volumes:
      - db-data:/data
    deploy:
      resources:
          limits:
            cpus: "2.0"

networks:
  backend:
    driver: bridge

volumes:
  db-data: