services:
  game:
    build:
      context: .
      dockerfile: bench.dockerfile
    hostname: game
    networks:
      - backend
    environment:
      - LISTEN_ADDR=0.0.0.0:5000
    ports:
      - "5000:5000"
    command: ["/game"]
    deploy:
      resources:
          limits:
            cpus: "1.0"
    volumes:
      - db-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 2s
      timeout: 2s
      retries: 3
  
  bot_client:
    build:
      context: .
      dockerfile: bench.dockerfile
    hostname: bot_client
    depends_on:
      game:
        condition: service_healthy
    networks:
      - backend
    environment:
      - SERVER_ADDR=game:5000
    command: ["/bot_client"]
    volumes:
      - db-data:/data
    
  python:
    build:
      context: .
      dockerfile: python.dockerfile
    hostname: python
    depends_on:
      game:
        condition: service_healthy
    ports:
      - "8888:8888"
    volumes:
      - db-data:/data

networks:
  backend:
    driver: bridge

volumes:
  db-data: