# Use an official Node.js runtime as the base image
FROM node:20 as builder

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the application
RUN npm run build

# Use a lightweight Node.js runtime for the final image
FROM node:20-alpine as runner

# Set the working directory in the container to /app
WORKDIR /app

# Copy the build output from the first stage
COPY --from=builder /app/dist ./dist

# Install a server to serve the application
RUN npm install -g serve

EXPOSE 3000

# Start the server
CMD ["serve", "-s", "dist"]